---
title: "Professional Experiences"
---



__Senior Statistical Programmer__  

[Gilead Science](https://www.gilead.com) 01/2013-Current 

-	Designed an interactive data visualization tool by Spotfire to  support data exploratory analysis and data review, gained popularity in cross function teams immediately with total users 500+ and totally visits 7000+, significantly reduced the ad hoc requests and increased the efficiency. .  
-	Lead the team to develop sample codes, write SAS macros, set the data infrastructure to streamline work process.
-	Programmed to apply statistical modeling/tests on over 50 clinical studies across therapeutic functions, communicated the results with multiple stockholders and influenced decision

__Statistical Programmer__ 

[PharmaNet/i3](http://www.inventivhealthclinical.com/global-reach.htm)  06/2011-01/2013

-	Programmed to performed statistical analysis on clinical data for new drug application to submit to FDA.
-	Built and maintained a biometrics database to support the company wise analysis work.
  
  
__SAS Programmer/Consultant__ 

[Amylin Pharmaceutical](http://www.inventivhealthclinical.com/global-reach.htm) 09/2009-06/2011

-	Performed statistical analysis and tests on clinical trial data using SAS or R for new drugs efficacy and safety.