---
title: "Projects"
---

__Hi, there, those are some cool projects I have done.__ 


 [Cracking the Kaggle project-Quora Question Pair](Kaggle_quora_pair.html)

 - Ranked on top 8% (bronze medal!) on the Kaggle leaderboard. 
 - NLP (natural language processing) handcrafted feature engineering. 
 - Used multiple machine learning algorithms (xgboost/neural network deep learning/random forest etc.) to build models.
 - Used advanced ensample skills, including stacking/bagging to further improve the model performance and make predictions.  
 
 [A Comprehensive Clinical Data Visulization with Spotfire](spotfire.pdf)

- Used spotfire to design and develop a comprehensive clinical data visulization tool 
- Scriped Ironpython to add advanced interative features.
- Due to the spotfire licence limitation, only PDF version is showing here.

 [How to use R Markdown and Gittub to make a personal website: A step-by-step tutorial and source code for this website](https://github.com/xuejieyu/xuejieyu.github.io)

- A step-by-step tutorial and source code for this website. 
_ A text version of tutorial will be updated soon. 

 What can you tell from your facebook account: an analysis of social network by python

- Used web crawler program to obtain data from facebook API.
- An analysis of social network by python networkx package. 